### ISSUE TITLE
API doesn't properly verify the TLS fingerprint

### ISSUE THREAD

**Issue by fortuna** [jadolg/outline-vpn-api#10]
The API checks the fingerprint on a test request in the constructor, but doesn't check the fingerprint in the actual requests, so they are not protected. You should validate the fingerprint on every request.

**Comment by fortuna** [comment]
This Node.js library had the same issue, and this is how they fixed it: https://github.com/murka/outlinevpn-api/commit/1b6cbfc6203ab0abee41a73f592226af72b31647

**Comment by jadolg** [comment]
I think this should do the job https://github.com/jadolg/outline-vpn-api/pull/11
Would you mind a quick review?

**Comment by jadolg** [comment]
Released in version 3.0.0
