### ISSUE TITLE
The api returns the key id as a string

### ISSUE THREAD

**Issue by fullkek** [jadolg/outline-vpn-api#22]
Hello. Thanks for the lib. 

The api returns the key id as a string. 
Need to cast to int or use str type for key_id.

![image](https://github.com/jadolg/outline-vpn-api/assets/59085306/d2c82b86-1b87-4db5-b2b2-df96073217f3)

![image](https://github.com/jadolg/outline-vpn-api/assets/59085306/7782a238-5c6c-4d54-956d-d2307bb6d3b2)

![image](https://github.com/jadolg/outline-vpn-api/assets/59085306/09973aac-52bd-408e-923d-23c538ac2817)

**Comment by jadolg** [comment]
Nice catch. I'll use `str` same as the API is returning.
